substitutions:
  name_of_device:       esp32-energy
  device_name_friendly: ESP32-Energy
  mqtt_location:        "FurnaceRoom"
  mqtt_device:          "ESP32-Energy"
  mqtt_sensor:          "ct-clamp-01"

esphome:
  name:                $name_of_device
  friendly_name:       $device_name_friendly
  name_add_mac_suffix: false
  platform:            ESP32
  board:               esp32dev

output:
  - platform: gpio
    pin:      2
    id:       onboard_led

light:
  - platform: binary
    name:     "Built-in LED"
    output:   onboard_led
    id:       led_light

# Enable logging
logger:
  level: VERBOSE
  logs:
    mqtt.component: ERROR
    mqtt.client:    ERROR

wifi:
  power_save_mode: NONE  # Options are NONE, LIGHT, and HIGH, with HIGH saving the most power.
  networks:
    - ssid: !secret     wifi_ssid
      password: !secret wifi_password
    - ssid: !secret     wifi_ssid_backup
      password: !secret wifi_password
    - ssid: !secret     wifi_ssid_work
      password: !secret wifi_pass_work

mqtt:
  broker: !secret broker_address
  on_connect:
    then:
      - light.turn_on: led_light
  on_disconnect:
    then:
      - light.turn_off: led_light
#  topic_prefix:   "$mqtt_location/$mqtt_device"

captive_portal:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key_esp32_energy

ota:
  password: !secret ota_password_esp32_energy

sensor:
  - platform:            template
    id:                  my_power
    name:                "Measured Power"
    lambda:              return id( adc_office ).state * 110 / 1000;  # Power = I * V / 1000.
    unit_of_measurement: 'kW'
    update_interval:     5s

  - platform: total_daily_energy
    name:     "Total Daily Power Usage"
    power_id: my_power

  - platform:          ct_clamp
    sensor:            adc_office
    name:              "raw"
    id:                ct_raw
    update_interval:   10s
    accuracy_decimals: 3

  - platform:          ct_clamp
    sensor:            adc_office
    sample_duration:   300ms
    name:              "Electricity usage (amps)"
    id:                ct_amps
    update_interval:   10s
    accuracy_decimals: 3
    filters:
      - calibrate_linear:
          - 0.003 -> 0       # Map a 0.003 reading to 0 Kw.
          - 0.147 -> 8.63    # Map a 0.147 reading to 8.63 Kw.

  - platform:            ct_clamp
    sensor:              adc_office
    sample_duration:     300ms
    name:                "Electricity usage"
    id:                  esp_watts
    update_interval:     10s
    accuracy_decimals:   3
    filters:
      - calibrate_linear:
          - 0.003 -> 0       # Map a 0.003 reading to 0 Kw.
          - 0.147 -> 8.63    # Map a 0.147 reading to 8.63 Kw.

      - lambda: return x * 150.0 / 1000;
    unit_of_measurement: "Kw"

  - platform:            ct_clamp
    sensor:              adc_phase_1
    sample_duration:     300ms
    name:                "Electricity usage 1"
    id:                  phase1_watts
    update_interval:     10s
    accuracy_decimals:   3
    filters:
      - calibrate_linear:
          - 0.003 -> 0       # Map a 0.003 reading to 0 Kw.
          - 0.147 -> 8.63    # Map a 0.147 reading to 8.63 Kw.

      - lambda: return x * 150.0 / 1000;
    unit_of_measurement: "Kw"

  ################
  # ADC settings #
  ################
  - platform:        adc
    name:            "Downstairs office"
    id:              adc_office
    pin:             34
    attenuation:     11db
    update_interval: 10s
    on_value:
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/$mqtt_sensor/ADC-Office-raw"
          payload: !lambda |-
                           return to_string( id( adc_office ).state );

  - platform:        adc
    name:            "Phase 1"
    id:              adc_phase_1
    pin:             36
    attenuation:     11db
    update_interval: 10s
    on_value:
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/Phase-01/ADC-Phase1-raw"
          payload: !lambda |-
                           return to_string( id( adc_phase_1 ).state );

  - platform:        adc
    name:            "Raw ADC"
    id:              adc_phase_2
    pin:             39
    attenuation:     11db
    update_interval: 10s
    on_value:
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/Phase-02/ADC-Phase2-raw"
          payload: !lambda |-
                           return to_string( id( adc_phase_2 ).state );

  - platform:            total_daily_energy    # This sensor will give you a Daily kW reading
    name:                "Phase 1 Daily Energy"
    unit_of_measurement: 'kWh'
    power_id:            phase1_watts
    accuracy_decimals:   3
    filters:
    device_class:        energy

  - platform:            wifi_signal       # Reports the WiFi signal strength/RSSI in dB
    name:                "WiFi Signal dB"
    id:                  wifi_signal_db
    unit_of_measurement: "dB"
    accuracy_decimals:   2
    update_interval:     30s
    entity_category:     "diagnostic"
    on_value:
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/rssi"
          payload: !lambda |-
                           return to_string( id( wifi_signal_db ).state );

text_sensor:
  - platform: wifi_info
    ip_address:
      name: $device_name_friendly IP address
      id:   ip_address
    ssid:
      name: $device_name_friendly connected SSID
    bssid:
      name: $device_name_friendly connected BSSID
    mac_address:
      name: $device_name_friendly MAC Address
      id:   mac_address
    scan_results:
      name: $device_name_friendly scan results

time:
  - platform: sntp
    id:       my_time

interval:
  - interval: 1min
    then:
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/mac"
          payload: !lambda |-
                           return to_string( id( mac_address ).state );
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/ip"
          payload: !lambda |-
                           return to_string( id( ip_address ).state );
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/$mqtt_sensor/ct_raw"
          payload: !lambda |-
                           return to_string( id( ct_raw ).state );
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/$mqtt_sensor/ct_amps"
          payload: !lambda |-
                           return to_string( id( ct_amps ).state );
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/$mqtt_sensor/esp_watts"
          payload: !lambda |-
                           return to_string( id( esp_watts ).state );
