# This is a calibration file for CT clamps connected to an ESP32.
# It has been stripped of everything which does not relate to energy measurement.
# The Current Transformer (CT) clamps are SCT013-000 (100A/50mA).
# The burden resistor is 22 Ohm.
# For my Quad-input board, the CTs connect to these pins:
# CT1 connects to ADC 1.0 on GPIO 36.
# CT2 connects to ADC 1.3 on GPIO 39.
# CT3 connects to ADC 1.6 on GPIO 34.
# CT4 connects to ADC 1.7 on GPIO 35.
esphome:
  name:     esp32-calibration
  platform: ESP32
  board:    esp32dev

sensor:
  - platform:            adc
    pin:                 GPIO36
    name:                "ADC36"
    unit_of_measurement: "A"
    update_interval:     10s

  - platform:            adc
    pin:                 GPIO39
    name:                "ADC39"
    unit_of_measurement: "A"
    update_interval:     10s

  - platform:            adc
    pin:                 GPIO34
    name:                "ADC34"
    unit_of_measurement: "A"
    update_interval:     10s

# Enable logging.
logger:
