substitutions:
  name_of_device:       esp32-energy
  device_name_friendly: ESP32-Energy
  mqtt_location:        "FurnaceRoom"
  mqtt_device:          "ESP32-Energy"
  mqtt_sensor:          "ct-clamp-01"

esphome:
  name:          $name_of_device
  friendly_name: $device_name_friendly
  platform:      ESP32
  board:         esp32dev

#wifi:
#  networks:
#    - ssid: !secret     wifi_ssid
#      password: !secret wifi_password

#  manual_ip:
#    static_ip: 192.168.0.223
#    gateway:   192.168.0.1
#    subnet:    255.255.255.0

#captive_portal:
#
#api:
#  encryption:
#    key: !secret encryption_key_esp32_energy
#
#ota:
#  password: !secret ota_password_esp32_energy

output:
  - platform: gpio
    pin:      2
    id:       onboard_led

light:
  - platform: binary
    name:     "Built-in LED"
    output:   onboard_led
    id:       led_light

# Enable logging
logger:
  level: VERBOSE
  logs:
    mqtt.component: ERROR
    mqtt.client:    ERROR

sensor:
  - platform:        adc
    pin:             GPIO36
    id:              adc_sensor
    attenuation:     11db
    update_interval: 10s


  - platform:          ct_clamp
    sensor:            adc_sensor
    name:              "Raw ADC value"
    update_interval:   10s
    accuracy_decimals: 5


  - platform:          ct_clamp
    sensor:            adc_sensor
    sample_duration:   300ms
    name:              "Amperes"
    update_interval:   10s
    accuracy_decimals: 3
    filters:
      - calibrate_linear:
          - 0.0097 -> 0
          - 0.1485 -> 1.746    # Value from KillAWatt


  - platform:            ct_clamp
    sensor:              adc_sensor
    sample_duration:     300ms
    name:                "Kilowatts"
    id:                  esp_watts
    update_interval:     10s
    accuracy_decimals:   3
    filters:
      - calibrate_linear:
          - 0.003 -> 0
          - 0.147 -> 8.63    # Value from KillAWatt
      - lambda: return x * 230.0 / 1000;
    unit_of_measurement: "Kw"


#  - platform:            total_daily_energy        # This sensor will give you a Daily kW reading
#    name:                "Total Daily Energy"
#    unit_of_measurement: 'kWh'
#    power_id:            esp_watts
#    accuracy_decimals:   3
#    filters:
#    device_class:        energy
