substitutions:
  name_of_device:       esp32-sht30-bmp280
  device_name_friendly: ESP32-SHT30-BMP280
  mqtt_location:        "MasterBedroom"
  mqtt_device:          "ESP32-02"

esphome:
  name:          $name_of_device
  friendly_name: $device_name_friendly
  platform:      ESP32
  board:         esp32dev

sensor:
  - <<: !include sht30.yaml
  - <<: !include bmp280.yaml
#  - <<: !include wifi_signal.yaml

text_sensor:
  - <<: !include wifi_info.yaml

interval:
  - <<: !include interval.yaml

#wifi:
#  - <<: !include wifi.yaml

i2c:
  - <<: !include i2c_esp32.yaml
