# Many of the substitutions are used solely to pass secrets to includes that are in subdirectories.
substitutions:
  name_of_device:           esp32-bme280-01
  device_name_friendly:     ESP32-BME280-01
  mqtt_location:            "MasterBedroom"
  mqtt_device:              "ESP32-01"
  api_password: !secret     master_esp32_bme280_api
  ota_password: !secret     master_esp32_bme280_ota
  wifi_ssid: !secret        wifi_ssid
  wifi_pass: !secret        wifi_password
  wifi_ssid_backup: !secret wifi_ssid_backup
  wifi_pass_backup: !secret wifi_password
  broker_address: !secret   broker_address
  led_gpio:                 GPIO2

# Root component.
esphome:
  name:     ${name_of_device}
  platform: ESP32
  board:    esp32dev

# Enable I2C communication.
i2c:
  - !include Components/Core/i2c_esp32.yaml

# Enable Wi-Fi.
wifi:
  !include Components/Core/wifi.yaml

# Enable the Home Assistant native API.
api:
  !include Components/Core/api.yaml

# Enable OTA updates.
ota:
  !include Components/Core/ota.yaml

# Enable logging.
logger:
  !include Components/Core/logger.yaml

# Enable MQTT publishing.
mqtt:
  !include Components/Core/mqtt.yaml

# Enable the BME280 sensor.
sensor:
  - !include Components/Sensors/bme280.yaml
  - !include Components/Sensors/wifi_signal.yaml
  - !include Components/Sensors/wifi_signal_percent.yaml

# The text_sensor handles many MQTT publishing duties.
text_sensor:
  - !include Components/Sensors/text_sensor.yaml

# The interval component handles many MQTT publishing duties.
interval:
  !include interval.yaml

# Enable the onboard LED as diagnostic output.
status_led:
  !include Components/Core/status_led.yaml
