# This is designed for a 30-pin ESP32 WROOM devkit.
# The burden resistor is 22 Ohm.
# The Current Transformer (CT) clamps are SCT013-000 (100A/50mA).
# The CTs connect to the first 4 pins next to the EN pin.
# CT1 connects to ADC 1.0 on GPIO 36.
# CT2 connects to ADC 1.3 on GPIO 39.
# CT3 connects to ADC 1.6 on GPIO 34.
# CT4 connects to ADC 1.7 on GPIO 35.
# SCL is on GPIO 22.
# SDA is on GPIO 21.
# ToDo: Configure the four ADC ports.
substitutions:
  name_of_device:           esp32-quad-energy
  device_name_friendly:     ESP32-QuadEnergy
  mqtt_location:            "FurnaceRoom"
  mqtt_device:              $device_name_friendly
  api_password: !secret     furnace_esp32_energy_api
  ota_password: !secret     furnace_esp32_energy_ota
  wifi_ssid: !secret        wifi_ssid
  wifi_pass: !secret        wifi_password
  wifi_ssid_backup: !secret wifi_ssid_backup
  wifi_pass_backup: !secret wifi_password
  broker_address: !secret   broker_address
  led_gpio:                 GPIO2

esphome:
  name:                $name_of_device
  friendly_name:       $device_name_friendly
  name_add_mac_suffix: false
  platform:            ESP32
  board:               esp32dev

sensor:
  - !include Components/Sensors/wifi_signal.yaml
  - !include Components/Sensors/wifi_signal_percent.yaml
  - !include Components/Sensors/uptime.yaml
  ################
  # ADC settings #
  ################
  - platform:        adc
    name:            "Phase 1 ADC"
    id:              adc_phase_1
    pin:             36
    attenuation:     11db
    update_interval: 10s
    on_value:
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/Phase-1/ADC-Phase1-raw"
          payload: !lambda |-
                           return to_string( id( adc_phase_1 ).state );

  - platform:        adc
    name:            "Phase 2 ADC"
    id:              adc_phase_2
    pin:             39
    attenuation:     11db
    update_interval: 10s
    on_value:
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/Phase-2/ADC-Phase2-raw"
          payload: !lambda |-
                           return to_string( id( adc_phase_2 ).state );

  - platform:        adc
    name:            "CT 3 ADC"
    id:              ct3_adc
    pin:             34
    attenuation:     11db
    update_interval: 10s
    on_value:
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/$mqtt_sensor/ADC-Office-raw"
          payload: !lambda |-
                           return to_string( id( ct3_adc ).state );

  - platform:        adc
    name:            "CT 4 ADC"
    id:              ct4_adc
    pin:             35
    attenuation:     11db
    update_interval: 10s
    on_value:
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/$mqtt_sensor/ADC-Office-raw"
          payload: !lambda |-
                           return to_string( id( ct4_adc ).state );

  - platform:            template
    id:                  my_power
    name:                "Measured overall power"
    lambda:              return ( ( id( adc_phase_1 ).state * 120 ) + ( id( adc_phase_2 ).state * 120 ) ) / 1000;  # Power = I * V / 1000.
    unit_of_measurement: 'kW'
    update_interval:     5s

  - platform: total_daily_energy
    name:     "Total Daily Power Usage"
    power_id: my_power
  - platform:          ct_clamp
    sensor:            adc_phase_1
    name:              "Phase 1 raw"
    id:                phase1_raw
    update_interval:   10s
    accuracy_decimals: 3

  - platform:          ct_clamp
    sensor:            adc_phase_1
    sample_duration:   300ms
    name:              "Phase 1 amps"
    id:                phase1_amps
    update_interval:   10s
    accuracy_decimals: 3
  #    filters:
  #      - calibrate_linear:
  #          - 0.0106 -> 0       # Map a 0.0106 reading to 0
  #          - 0.2566 -> 10.96   # Map a 0.2566 reading to 10.96

  - platform: total_daily_energy
    name:     "Total Daily Power Usage"
    power_id: my_power
  - platform:          ct_clamp
    sensor:            adc_phase_2
    name:              "Phase 2 raw"
    id:                phase2_raw
    update_interval:   10s
    accuracy_decimals: 3

  - platform:          ct_clamp
    sensor:            adc_phase_2
    sample_duration:   300ms
    name:              "Phase 2 amps"
    id:                phase2_amps
    update_interval:   10s
    accuracy_decimals: 3
  #    filters:
  #      - calibrate_linear:
  #          - 0.01077 -> 0      # Map a 0.01077 reading to 0
  #          - 0.04193 -> 1.65   # Map a 0.04193 reading to 1.65

  - platform:          ct_clamp
    sensor:            ct3_adc
    name:              "Office raw"
    id:                office_raw
    update_interval:   10s
    accuracy_decimals: 3

  - platform:          ct_clamp
    sensor:            ct3_adc
    sample_duration:   300ms
    name:              "Office amps"
    id:                office_amps
    update_interval:   10s
    accuracy_decimals: 3
  #    filters:
  #      - calibrate_linear:
  #          - 0.011 -> 0        # Map a 0.011 reading to 0
  #          - 0.027 -> 1.764    # Map a 0.027 reading to 1.764

  - platform:            ct_clamp
    sensor:              adc_phase_1
    sample_duration:     300ms
    name:                "Phase 1 watts"
    id:                  phase1_watts
    update_interval:     10s
    accuracy_decimals:   3
    unit_of_measurement: "Kw"
    filters:
      #      - calibrate_linear:
      #          - 0.009 -> 0         # Map a 0.009 reading to 0 Kw.
      #          - 0.011 -> 11.4      # Map a 0.011 reading to 11.4 Kw.
      #          - 0.256 -> 1223.136  # Map a 0.256 reading to 1223.136 Kw.
      - lambda: return x * 150.0 / 1000;

  - platform:            total_daily_energy    # This sensor will give you a Daily kW reading
    name:                "Phase 1 Daily Energy"
    unit_of_measurement: 'kWh'
    power_id:            phase1_watts
    accuracy_decimals:   3
    filters:
    device_class:        energy

  - platform:            ct_clamp
    sensor:              adc_phase_2
    sample_duration:     300ms
    name:                "Phase 2 watts"
    id:                  phase2_watts
    update_interval:     10s
    accuracy_decimals:   3
    filters:
      #      - calibrate_linear:
      #          - 0.0095 -> 0        # Map a 0.0095 reading to 0 Kw.
      #          - 0.0415 -> 196.185  # Map a 0.0415 reading to 196.185 Kw.
      - lambda: return x * 150.0 / 1000;
    unit_of_measurement: "Kw"

  - platform:            total_daily_energy    # This sensor will give you a Daily kW reading
    name:                "Phase 2 Daily Energy"
    unit_of_measurement: 'kWh'
    power_id:            phase2_watts
    accuracy_decimals:   3
    filters:
    device_class:        energy

  - platform:            ct_clamp
    sensor:              ct3_adc
    sample_duration:     300ms
    name:                "Office watts"
    id:                  office_watts
    update_interval:     10s
    accuracy_decimals:   3
    filters:
      #      - calibrate_linear:
      #          - 0.011 -> 0          # Map a 0.011 reading to 0 Kw.
      #          - 0.0276 -> 208.152   # Map a 0.0276 reading to 208.152 Kw.
      - lambda: return x * 150.0 / 1000;
    unit_of_measurement: "Kw"

  - platform:            total_daily_energy    # This sensor will give you a Daily kW reading
    name:                "Office Daily Energy"
    unit_of_measurement: 'kWh'
    power_id:            office_watts
    accuracy_decimals:   3
    filters:
    device_class:        energy


  - platform:            wifi_signal       # Reports the WiFi signal strength/RSSI in dB
    name:                "WiFi Signal dB"
    id:                  wifi_signal_db
    unit_of_measurement: "dB"
    accuracy_decimals:   2
    update_interval:     30s
    entity_category:     "diagnostic"
    on_value:
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/rssi"
          payload: !lambda |-
                           return to_string( id( wifi_signal_db ).state );

time:
  - platform: sntp
    id:       my_time

# The interval component handles many MQTT publishing duties.
interval:
  - interval: 1min
    then:
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/mac"
          payload: !lambda |-
                           return to_string( id( mac_address ).state );
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/ip"
          payload: !lambda |-
                           return to_string( id( ip_address ).state );
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/$mqtt_sensor/phase1_raw"
          payload: !lambda |-
                           return to_string( id( phase1_raw ).state );
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/$mqtt_sensor/phase1_amps"
          payload: !lambda |-
                           return to_string( id( phase1_amps ).state );
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/$mqtt_sensor/phase1_watts"
          payload: !lambda |-
                           return to_string( id( phase1_watts ).state );
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/$mqtt_sensor/phase2_raw"
          payload: !lambda |-
                           return to_string( id( phase2_raw ).state );
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/$mqtt_sensor/phase2_amps"
          payload: !lambda |-
                           return to_string( id( phase2_amps ).state );
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/$mqtt_sensor/phase2_watts"
          payload: !lambda |-
                           return to_string( id( phase2_watts ).state );
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/$mqtt_sensor/office_raw"
          payload: !lambda |-
                           return to_string( id( office_raw ).state );
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/$mqtt_sensor/office_amps"
          payload: !lambda |-
                           return to_string( id( office_amps ).state );
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/$mqtt_sensor/office_watts"
          payload: !lambda |-
                           return to_string( id( office_watts ).state );

# Enable I2C communication.
i2c:
  - !include Components/Core/i2c_esp32.yaml

# Enable Wi-Fi.
wifi:
  !include Components/Core/wifi.yaml

# Enable the Home Assistant native API.
api:
  !include Components/Core/api.yaml

# Enable OTA updates.
ota:
  !include Components/Core/ota.yaml

# Enable logging.
logger:
  !include Components/Core/logger.yaml

# Enable MQTT publishing.
mqtt:
  !include Components/Core/mqtt.yaml

# The text_sensor handles many MQTT publishing duties.
text_sensor:
  - !include Components/TextSensor/wifi_info.yaml

# Enable the onboard LED as diagnostic output.
status_led:
  !include Components/Core/status_led.yaml

# Expose the node state for Home Assistant.
binary_sensor:
  - !include Components/BinarySensors/status.yaml
