substitutions:
  name_of_device:           esp32-18650
  device_name_friendly:     ESP32-18650
  mqtt_location:            "Mobile"
  mqtt_device:              $device_name_friendly
  api_password: !secret     esp32_18650_api
  ota_password: !secret     esp32_18650_ota
  wifi_ssid: !secret        wifi_ssid
  wifi_pass: !secret        wifi_password
  wifi_ssid_backup: !secret wifi_ssid_backup
  wifi_pass_backup: !secret wifi_password
  broker_address: !secret   broker_address
  led_gpio:                 GPIO2

esphome:
  name:          $name_of_device
  friendly_name: $device_name_friendly

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable I2C communication.
i2c:
  - !include Components/Core/i2c_esp32.yaml

# Enable Wi-Fi.
wifi:
  !include Components/Core/wifi.yaml

# Enable the Home Assistant native API.
api:
  !include Components/Core/api.yaml

# Enable OTA updates.
ota:
  !include Components/Core/ota.yaml

# Enable logging.
logger:
  !include Components/Core/logger.yaml

# Enable MQTT publishing.
mqtt:
  !include Components/Core/mqtt.yaml

# Enable the BME280 sensor.
sensor:
  - !include Components/Sensors/wifi_signal.yaml
  - !include Components/Sensors/wifi_signal_percent.yaml

# The text_sensor handles many MQTT publishing duties.
text_sensor:
  - !include Components/Sensors/text_sensor.yaml

# The interval component handles many MQTT publishing duties.
interval:
  !include Components/Core/interval.yaml

# Expose the node state for Home Assistant.
binary_sensor:
  !include Components/Core/binary_sensor.yaml
