# esphome.yaml
substitutions:
  name_of_device:       esp32-bme280-01
  device_name_friendly: ESP32-BME280-01
  mqtt_location:        "MasterBedroom"
  mqtt_device:          "ESP32-01"

esphome:
  name:     my-esp32
  platform: ESP32
  board:    esp32dev

i2c:
  - !include i2c_esp32.yaml

sensor:
  # Include the bme280.yaml file for the BME280 sensor configuration
  - !include bme280.yaml

# Include the wifi.yaml file for Wi-Fi configuration
wifi:
  !include wifi.yaml

mqtt:
#  broker: !secret broker_address
  !include mqtt.yaml

interval:
  !include interval.yaml

text_sensor:
  !include text_sensor.yaml

# Enable logging
logger:
  level: DEBUG
