# https://devices.esphome.io/devices/lilygo-tdisplay-s3/

# https://esphome.io/components/substitutions/
substitutions:
  device_name:              t-displays3
  device_name_friendly:     "T-Display-S3"  # Quoted to ensure spaces are handled correctly.
  mqtt_location:            "Mobile"
  mqtt_device:              ${device_name_friendly}
  api_password: !secret     lilygo_t_display_s3_api
  ota_password: !secret     lilygo_t_display_s3_ota
  wifi_ssid: !secret        wifi_ssid
  wifi_pass: !secret        wifi_password
  wifi_ssid_backup: !secret wifi_ssid_backup
  wifi_pass_backup: !secret wifi_password
  broker_address: !secret   broker_address
  led_gpio:                 GPIO2


# The ESPHome section sets the required node name and optional settings.
# https://esphome.io/components/esphome/
esphome:
  name:          ${device_name}
  friendly_name: ${device_name_friendly}
  area:          ${mqtt_location}
  comment:       "https://lilygo.cc/products/t-display-s3"


# https://esphome.io/components/esp32/
esp32:
  variant: esp32s3
  framework:
    type: esp-idf
  flash_size: 16MB


# https://esphome.io/components/api/
api:
  !include Components/Core/api.yaml


# https://esphome.io/components/ota/
ota:
  !include Components/Core/ota.yaml


# https://esphome.io/components/wifi/
wifi:
  !include Components/Core/wifi.yaml


# https://esphome.io/components/captive_portal/
captive_portal:


# Enable MQTT publishing.
# https://esphome.io/components/mqtt/
mqtt:
  !include Components/Core/mqtt.yaml


# https://esphome.io/components/logger/
logger:
  #level: WARN
  !include Components/Core/logger.yaml


# The QWIIC port next to the USB-C port.
# https://esphome.io/components/i2c/
i2c:
  sda:       GPIO43
  scl:       GPIO44
  scan:      true
  frequency: 400kHz


# https://esphome.io/components/sensor/
sensor:
  - !include Components/Sensors/wifi_signal.yaml
  - !include Components/Sensors/wifi_signal_percent.yaml
  - !include Components/Sensors/uptime.yaml
  # I have an Adafruit SHT40 plugged into the QWIIC port next to the USB-C port.
  # This sht4x.yaml file requires MQTT because it calls mqtt.publish with every on_value.
  # https://esphome.io/components/sensor/sht4x/
  - !include Components/Sensors/sht4x.yaml
  # https://next.esphome.io/components/sensor/internal_temperature/
  - platform: internal_temperature
    name:     "Internal Temperature"
    update_interval: 20s


# https://esphome.io/components/binary_sensor/
binary_sensor:
  - platform: gpio
    pin:
      # Obviously this is the "boot" button on the left when USB is down.
      number: GPIO0
      ignore_strapping_warning: true
      inverted: true
    name: "Button 1"
  - platform: gpio
    pin:
      # Button on the right when USB is down.
      number: GPIO14
      inverted: true
    name: "Button 2"


# https://esphome.io/components/output/
output:
  - platform: ledc
    frequency: 2000
    pin: GPIO38
    id: backlight_output


# https://esphome.io/components/light/
light:
  - platform: monochromatic
    output: backlight_output
    name: LCD Backlight
    id: led
    restore_mode: ALWAYS_ON
    default_transition_length: 0s


# https://esphome.io/components/spi/
spi:
  type: octal
  clk_pin: GPIO8
  data_pins:
    - GPIO39
    - GPIO40
    - GPIO41
    - GPIO42
    - ignore_strapping_warning: true
      number: GPIO45
    - ignore_strapping_warning: true
      number: GPIO46
    - GPIO47
    - GPIO48


# https://esphome.io/components/psram/
psram:
  speed: 80MHz
  mode: octal


# https://esphome.io/components/time/
time:
  - platform: homeassistant
    id: ha_time


# https://esphome.io/components/font/
font:
  - file: "gfonts://Roboto"
    id: font_large
    size: 30
  - file: "gfonts://Roboto"
    id: font_medium
    size: 20


# https://esphome.io/components/color/
color:
  - id: color_black
    hex: "000000"
  - id: color_gray
    hex: "AAAAAA"


# https://esphome.io/components/image/
image:
  - file: mdi:thermometer
    id: temperature_icon
    resize: 30x30
    type: rgb
  - file: mdi:water-percent
    id: humidity_icon
    resize: 30x30
    type: rgb


# https://esphome.io/components/display/
display:
  # https://esphome.io/components/display/mipi_spi/
  - platform: mipi_spi
    # This model is a ST7789 with a 170x320 resolution.
    model: t-display-s3
    # 270 has the USB port on the left.
    rotation: 90
    show_test_card: false
    lambda: |-
          int screen_height = it.get_height();

          // Time & Date
          it.strftime( 10, 10, id( font_large ), id( color_gray ), TextAlign::TOP_LEFT, "%H:%M", id( ha_time ).now() );
          it.strftime( 10, 60, id( font_medium ), id( color_gray ), TextAlign::TOP_LEFT, "%A, %B %d", id( ha_time ).now() );

          it.image( 10, 90, id( temperature_icon ) );
          it.printf( 80, 90, id( font_medium ), Color( color_gray ), "%.1f°C", id( sht4x_temp ).state );
          it.image( 10, 120, id( humidity_icon ) );
          it.printf( 80, 120, id( font_medium ), Color( color_gray ), "%.1f%%", id( sht4x_humidity ).state );
