substitutions:
  name_of_device:           back-porch
  device_name_friendly:     Back porch
  mqtt_location:            "BackPorch"
  mqtt_device:              $device_name_friendly
  api_password: !secret     lilygo_t_camera_api
  ota_password: !secret     lilygo_t_camera_ota
  wifi_ssid: !secret        wifi_ssid
  wifi_pass: !secret        wifi_password
  wifi_ssid_backup: !secret wifi_ssid_backup
  wifi_pass_backup: !secret wifi_password
  broker_address: !secret   broker_address
  led_gpio:                 GPIO2

esphome:
  name:          $name_of_device
  friendly_name: $device_name_friendly
  platform:      ESP32
  board:         esp-wrover-kit

binary_sensor:
  - !include Components/BinarySensors/status.yaml
  - platform:     gpio
    pin:          GPIO19 #33
    name:         $device_name_friendly PIR
    device_class: motion
  - platform: gpio
    pin:
      number:   GPIO15 #34
      inverted: True
    name:     $device_name_friendly Button

esp32_camera:
  name:              $device_name_friendly Camera
  external_clock:
    pin:       GPIO4 #32 not sure!
    frequency: 20MHz
  i2c_pins:
    sda: GPIO18 #13
    scl: GPIO23 #12
  data_pins: [GPIO34, GPIO13, GPIO14, GPIO35, GPIO39, GPIO38, GPIO37, GPIO36] #[GPIO5, GPIO14, GPIO4, GPIO15, GPIO18, GPIO23, GPIO36, GPIO39]
  vsync_pin:         GPIO5 #27
  href_pin:          GPIO27 #25
  pixel_clock_pin:   GPIO25 #19
  # power_down_pin: GPIO26 No PWD GPIO existing
  resolution:        800x600
  jpeg_quality:      10
  vertical_flip:     true
  horizontal_mirror: false

font:
  - file: "fonts/times-new-roman.ttf"
    id:   tnr1
    size: 20
  - file: "fonts/times-new-roman.ttf"
    id:   tnr2
    size: 35

time:
  - platform: homeassistant
    id:       homeassistant_time

display:
  - platform: ssd1306_i2c
    model:    "SSD1306 128x64"
    address:  0x3C
    rotation: 180°
    lambda:   |-
              it.strftime(64, 0, id(tnr1), TextAlign::TOP_CENTER,"%Y-%m-%d", id(homeassistant_time).now());
              it.strftime(64, 64, id(tnr2), TextAlign::BASELINE_CENTER, "%H:%M", id(homeassistant_time).now());

# Enable I2C communication.
i2c:
  - !include Components/Core/i2c_esp32.yaml

# Enable Wi-Fi.
wifi:
  !include Components/Core/wifi.yaml

# Enable the Home Assistant native API.
api:
  !include Components/Core/api.yaml

# Enable OTA updates.
ota:
  !include Components/Core/ota.yaml

# Enable logging.
logger:
  !include Components/Core/logger.yaml

# Enable MQTT publishing.
mqtt:
  !include Components/Core/mqtt.yaml

# Enable various sensors.
sensor:
  - !include Components/Sensors/wifi_signal.yaml
  - !include Components/Sensors/wifi_signal_percent.yaml
  - !include Components/Sensors/uptime.yaml

# The text_sensor handles many MQTT publishing duties.
text_sensor:
  - !include Components/TextSensor/wifi_info.yaml

# The interval component handles many MQTT publishing duties.
interval:
  !include Components/Core/interval.yaml

# Enable the onboard LED as diagnostic output.
status_led:
  !include Components/Core/status_led.yaml
