substitutions:
  name_of_device:           m5stampc3
  device_name_friendly:     M5StampC3
  mqtt_location:            "Mobile"
  mqtt_device:              $device_name_friendly
  api_password: !secret     m5stamp_api
  ota_password: !secret     m5stamp_ota
  wifi_ssid: !secret        wifi_ssid
  wifi_pass: !secret        wifi_password
  wifi_ssid_backup: !secret wifi_ssid_backup
  wifi_pass_backup: !secret wifi_password
  broker_address: !secret   broker_address
  led_gpio:                 GPIO2

esphome:
  name:          $name_of_device
  friendly_name: $device_name_friendly
  comment:       "https://docs.m5stack.com/en/core/stamp_c3"
  area:          $mqtt_location

esp32:
  board:   esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    # type: esp-idf
    type:    arduino
    version: recommended

wifi:
  ssid:     !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "M5StampC3 Fallback"
    password: "ajh14113"

logger:
  level: VERBOSE

# Enable the Home Assistant native API.
api:
  !include Components/Core/api.yaml

# Enable OTA updates.
ota:
  !include Components/Core/ota.yaml

# # Example LED (if you have one connected to a GPIO, or using the built in LED)
# light:
#   - platform: gpio
#     name: "M5StampC3 LED"
#     output: GPIO2
#     id: my_led

# # Example Binary Sensor (Button)
# binary_sensor:
#   - platform: gpio
#     pin:
#       number: GPIO3
#       mode: INPUT_PULLUP
#       inverted: true # Adjust if needed
#     name: "M5StampC3 Button"
#     on_press:
#       - light.toggle: my_led

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
