esphome:
  name: familyroom8266
  friendly_name: FamilyRoom8266

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # use_address: "192.168.55.4"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_ssid_backup
    password: !secret wifi_password

captive_portal:

i2c:
  sda: 4
  scl: 5
  scan: true
  frequency: 400kHz

mqtt:
  broker: 192.168.55.200

sensor:
  - platform: htu21d
    temperature:
      filters:
      - filter_out: 998.00
      - lambda: return ( x * 1.8 ) + 32.0;
      unit_of_measurement: "°F"
      name: "Family room temperature"
    humidity:
      filters:
      - filter_out: 998.00
      unit_of_measurement: "%"
      name: "Family room humidity"
    update_interval: 20s
