# https://esphome.io/components/substitutions/
substitutions:
  device_name:              office-qtpy
  device_name_friendly:     "Office QTPy"  # Quoted to ensure spaces are handled correctly.
  mqtt_location:            "Office"
  mqtt_device:              $device_name_friendly
  api_password: !secret     office_qtpy_api
  ota_password: !secret     office_qtpy_ota
  wifi_ssid: !secret        wifi_ssid
  wifi_pass: !secret        wifi_password
  wifi_ssid_backup: !secret wifi_ssid_backup
  wifi_pass_backup: !secret wifi_password
  broker_address: !secret   broker_address
  led_gpio:                 GPIO2


# The ESPHome section sets the required node name and optional settings.
# https://esphome.io/components/esphome/
esphome:
  device_name:   ${device_name}
  friendly_name: ${device_name_friendly}
  area:          ${mqtt_location}
  comment:       "https://www.adafruit.com/product/5325"
  on_boot:
    - output.turn_on: neopixel_power

# https://esphome.io/components/esp32/
esp32:
  board:   adafruit_qtpy_esp32s2
  variant: esp32s2
  framework:
    type: arduino

# https://esphome.io/components/captive_portal/
captive_portal:

# Enable I2C communication.
# https://esphome.io/components/i2c/
i2c:
  - !include Components/Core/i2c_qtpy_s2.yaml

# Enable Wi-Fi.
# https://esphome.io/components/wifi/
wifi:
  !include Components/Core/wifi.yaml

# Enable the Home Assistant native API.
# https://esphome.io/components/api/
api:
  !include Components/Core/api.yaml

# Enable OTA updates.
# https://esphome.io/components/ota/
ota:
  !include Components/Core/ota.yaml

# Enable logging.
# https://esphome.io/components/logger/
logger:
  !include Components/Core/logger.yaml

# Enable MQTT publishing.
# https://esphome.io/components/mqtt/
mqtt:
  !include Components/Core/mqtt.yaml

# Enable the BME280 sensor.
# https://esphome.io/components/sensor/
sensor:
  - !include Components/Sensors/sht4x.yaml
  - !include Components/Sensors/wifi_signal.yaml
  - !include Components/Sensors/wifi_signal_percent.yaml
  - !include Components/Sensors/uptime.yaml
  - platform: internal_temperature
    name:     "Internal Temperature"

# The text_sensor handles many MQTT publishing duties.
# https://esphome.io/components/text_sensor/
text_sensor:
  - !include Components/TextSensor/wifi_info.yaml

# The interval component handles many MQTT publishing duties.
# https://esphome.io/components/interval/
interval:
  !include Components/Core/interval.yaml

# Safe mode used to be part of the OTA component.
# https://esphome.io/components/safe_mode/
safe_mode:
  !include Components/Core/safe_mode.yaml

# GPIO output for NeoPixel power
# https://esphome.io/components/output/
output:
  - platform: gpio
    pin:      GPIO38
    id:       neopixel_power

# Enable the onboard NeoPixel LED as diagnostic output.
# https://esphome.io/components/light/
light:
  - platform:  esp32_rmt_led_strip
    id:        onboard_neopixel
    rgb_order: GRB
    pin:       GPIO39
    num_leds:  1
    # rmt_channel: 0
    chipset:   ws2812
    name:      "Onboard Neopixel"

# Binary sensor to control the NeoPixel status LED and expose the node state for Home Assistant.
# https://esphome.io/components/binary_sensor/
binary_sensor:
  - platform: status
    name:     "Device Status"
    id:       device_status
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: device_status
            then:
              - light.turn_on:
                  id:         onboard_neopixel
                  brightness: 50%
                  red:        0%
                  green:      100%
                  blue:       0%
            else:
              - light.turn_on:
                  id:         onboard_neopixel
                  brightness: 100%
                  red:        100%
                  green:      0%
                  blue:       0%
