# https://esphome.io/components/substitutions/
substitutions:
  name_of_device:           qtpy-bme688
  device_name_friendly:     QTPy BME688
  mqtt_location:            "Kitchen"
  mqtt_device:              $device_name_friendly
  api_password: !secret     qtpy_bme688_api
  ota_password: !secret     qtpy_bme688_ota
  wifi_ssid: !secret        wifi_ssid
  wifi_pass: !secret        wifi_password
  wifi_ssid_backup: !secret wifi_ssid_backup
  wifi_pass_backup: !secret wifi_password
  broker_address: !secret   broker_address
  led_gpio:                 GPIO2


# The ESPHome section sets the required node name and optional settings.
# https://esphome.io/components/esphome/
esphome:
  name:          $name_of_device
  friendly_name: $device_name_friendly
  comment:       "https://www.adafruit.com/product/5325"
  area:          $mqtt_location
  on_boot:
    - output.turn_on: neopixel_power


# https://esphome.io/components/esp32/
esp32:
  board:   adafruit_qtpy_esp32s2
  variant: esp32s2
  framework:
    # ToDo: Consider migrating to the esp-idf framework, as it3 produces smaller binaries and builds faster.
    type: arduino


# https://esphome.io/components/captive_portal/
captive_portal:


# Enable I2C communication.
# https://esphome.io/components/i2c/
i2c:
  - !include Components/Core/i2c_qtpy_s2.yaml


# Enable Wi-Fi.
# https://esphome.io/components/wifi/
wifi:
  !include Components/Core/wifi.yaml


# Enable the Home Assistant native API.
# https://esphome.io/components/api/
api:
  !include Components/Core/api.yaml


# Enable Over-The-Air updates.
# https://esphome.io/components/ota/
ota:
  !include Components/Core/ota.yaml


# Enable logging.
# https://esphome.io/components/logger/
logger:
  !include Components/Core/logger.yaml


# Enable MQTT publishing.
# https://esphome.io/components/mqtt/
mqtt:
  !include Components/Core/mqtt.yaml


# Enable the BME688 and other sensors.
# https://esphome.io/components/sensor/
sensor:
  - !include Components/Sensors/bme688.yaml
  - !include Components/Sensors/wifi_signal.yaml
  - !include Components/Sensors/wifi_signal_percent.yaml
  - !include Components/Sensors/uptime.yaml
  - platform: internal_temperature
    name:     "Internal Temperature"


# The text_sensor handles many MQTT publishing duties.
# https://esphome.io/components/text_sensor/
text_sensor:
  - !include Components/TextSensor/wifi_info.yaml
  # - !include Components/TextSensor/bme688_air_quality.yaml


# The interval component handles many MQTT publishing duties.
# https://esphome.io/components/interval/
interval:
  !include Components/Core/interval.yaml


# Safe mode used to be part of the Over-The-Air component.
# https://esphome.io/components/safe_mode/
safe_mode:
  !include Components/Core/safe_mode.yaml


# GPIO output for NeoPixel power.
# This allows turning the Neopixel on and off.
# https://esphome.io/components/output/
output:
  - platform: gpio
    pin:      GPIO38
    id:       neopixel_power


# Enable the onboard NeoPixel LED as diagnostic output.
# https://esphome.io/components/light/
light:
  - platform:  esp32_rmt_led_strip
    name:      "Onboard Neopixel"
    id:        onboard_neopixel
    rgb_order: GRB
    pin:       GPIO39
    num_leds:  1
    chipset:   ws2812


# Binary sensor to control the NeoPixel status LED and expose the node state for Home Assistant.
# https://esphome.io/components/binary_sensor/
binary_sensor:
  - platform: status
    name:     "Device Status"
    id:       device_status
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: device_status
            then:
              # Green for "online and healthy".
              - light.turn_on:
                  id:         onboard_neopixel
                  brightness: 50%
                  red:        0%
                  green:      100%
                  blue:       0%
            else:
              # Bright red for "offline or in safe mode".
              - light.turn_on:
                  id:         onboard_neopixel
                  brightness: 100%
                  red:        100%
                  green:      0%
                  blue:       0%
