# https://devices.esphome.io/devices/sonoff-s31/
substitutions:
  device_name:              s31-01
  device_name_friendly:     S31-01
  mqtt_location:            "Office"
  mqtt_device:              ${device_name_friendly}
  api_password: !secret     s31_01_api
  ota_password: !secret     s31_01_ota
  broker_address: !secret   broker_address
  led_gpio:                 GPIO21


esp8266:
  board: esp01_1m


# Enable Wi-Fi.
# https://esphome.io/components/wifi/
wifi:
  !include Components/Core/wifi.yaml


captive_portal:


# The ESPHome section sets the required node name and optional settings.
# https://esphome.io/components/esphome/
esphome:
  name:          ${device_name}
  friendly_name: ${device_name_friendly}
  area:          ${mqtt_location}
  comment:       "https://devices.esphome.io/devices/sonoff-s31/"

# https://esphome.io/components/esp32/
# esp32:
#   board: esp32-s3-devkitc-1
#   framework:
#     type: esp-idf

# https://esphome.io/components/esp8266/
# esp8266:
#   board: esp12e
#   early_pin_init: false
#   restore_from_flash: false # Set to true to use one of the switch's RESTORE_X restore_mode options

# Enable logging
# https://esphome.io/components/logger/
logger:
  baud_rate: 0 # (UART logging interferes with cse7766)
  logs:
    sensor: WARN # (Overide any global setting, to VERBOSE will spamming the cse7766 sensors)

# Enable the Home Assistant native API.
# https://esphome.io/components/api/
api:
  encryption:
    # key: "3OSR4IYfPQ4PK06DcATDahcSrHf7K17egoProv3FhUk="
    key: $api_password

# Enable OTA updates.
# https://esphome.io/components/ota/
ota:
  - platform: esphome
    # password: "630489bd2a8ba455ce16a6e20d08b9c6"
    password: $ota_password

# Enable Wi-Fi.
# https://esphome.io/components/wifi/
# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password
#   min_auth_mode: WPA2  # Or WPA3 for ESP32 if all your networks support it
#   ap:
#     ssid: "Fallback Hotspot"
#     password: !secret wifi_pass_hotspot

# https://esphome.io/components/captive_portal/
# captive_portal:

# https://esphome.io/components/uart/
uart:
  rx_pin:    RX
  baud_rate: 4800
  parity:    EVEN

# https://esphome.io/components/time/
time:
  - platform: sntp #(required for total_daily_energy)
    id:       my_time

# https://esphome.io/components/sensor/
sensor:
  - platform: cse7766
    current:
      name: "Current"
    voltage:
      name: "Voltage"
    power:
      name: "Power"
      id:   my_power
    energy:
      name: "Energy"
  - platform:            total_daily_energy
    name:                "Total Daily Energy"
    power_id:            my_power
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh

# https://esphome.io/components/status_led/
status_led:
  pin:
    number:   GPIO13
    inverted: true

# https://esphome.io/components/switch/
switch:
  - platform:     gpio
    name:         "Relay"
    pin:          GPIO12
    id:           relay
    restore_mode: RESTORE_DEFAULT_ON # Powering the relay may cause damage or instability when the programmer is supplying Vcc.

# https://esphome.io/components/binary_sensor/
binary_sensor:
  - platform: gpio
    pin:
      number:   GPIO0
      mode:     INPUT_PULLUP
      inverted: true
    name:     "Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name:     "Status"












# # https://devices.esphome.io/devices/sonoff-s31/
# substitutions:
#   device_name:              s31-01
#   device_name_friendly:     S31-01
#   mqtt_location:            "Office"
#   mqtt_device:              ${device_name_friendly}
#   api_password: !secret     s31_01_api
#   ota_password: !secret     s31_01_ota
#   broker_address: !secret   broker_address
#   led_gpio:                 GPIO21

# # https://esphome.io/components/esphome/
# esphome:
#   name:          $device_name
#   friendly_name: $device_name_friendly
#   comment:       "https://devices.esphome.io/devices/sonoff-s31/"
#   area:          ${mqtt_location}

# # https://esphome.io/components/esp32/
# esp32:
#   board: esp32-s3-devkitc-1
#   framework:
#     type: esp-idf

# # https://esphome.io/components/esp8266/
# # esp8266:
# #   board: esp12e
# #   early_pin_init: false
# #   restore_from_flash: false # Set to true to use one of the switch's RESTORE_X restore_mode options

# # Enable logging
# # https://esphome.io/components/logger/
# logger:
#   baud_rate: 0 # (UART logging interferes with cse7766)
#   logs:
#     sensor: WARN # (Overide any global setting, to VERBOSE will spamming the cse7766 sensors)

# # Enable the Home Assistant native API.
# # https://esphome.io/components/api/
# api:
#   encryption:
#     # key: "x4aky8QpEEb3FxHXgQtjJMMgt/lWooFnu+Bx4UCwL3I="
#     key: $api_password

# # Enable OTA updates.
# # https://esphome.io/components/ota/
# ota:
#   - platform: esphome
#     # password: "f5278d59c013008e37595679f609582d"
#     password: $ota_password

# # Enable Wi-Fi.
# # https://esphome.io/components/wifi/
# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password
#   ap:
#     ssid: "Fallback Hotspot"
#     password: !secret wifi_pass_hotspot

# # https://esphome.io/components/captive_portal/
# captive_portal:

# # https://esphome.io/components/uart/
# uart:
#   rx_pin: RX
#   baud_rate: 4800
#   parity: EVEN

# # https://esphome.io/components/time/
# time:
#   - platform: sntp #(required for total_daily_energy)
#     id: my_time

# # https://esphome.io/components/sensor/
# sensor:
#   - platform: cse7766
#     current:
#       name: "Current"
#     voltage:
#       name: "Voltage"
#     power:
#       name: "Power"
#       id: my_power
#     energy:
#       name: "Energy"
#   - platform: total_daily_energy
#     name: "Total Daily Energy"
#     power_id: my_power
#     filters:
#         # Multiplication factor from W to kW is 0.001
#         - multiply: 0.001
#     unit_of_measurement: kWh

# # https://esphome.io/components/status_led/
# status_led:
#   pin:
#     number: GPIO13
#     inverted: true

# # https://esphome.io/components/switch/
# switch:
#   - platform: gpio
#     name: "Relay"
#     pin: GPIO12
#     id: relay
#     restore_mode: ALWAYS_OFF # Powering the relay may cause damage or instability when the programmer is supplying Vcc.

# # https://esphome.io/components/binary_sensor/
# binary_sensor:
#   - platform: gpio
#     pin:
#       number: GPIO0
#       mode: INPUT_PULLUP
#       inverted: true
#     name: "Button"
#     on_press:
#       - switch.toggle: relay
#   - platform: status
#     name: "Status"
