esphome:
  name: esphome01
  includes:
    - F:\Code\Libraries\DFRobot_SHT20-master\DFRobot_SHT20.h
    - F:\Code\Libraries\DFRobot_SHT20-master\DFRobot_SHT20.cpp
    - SHT20.h

esp8266:
  board: nodemcuv2
  board_flash_mode: dout

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret default_pass

ota:
  password: !secret default_pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

# Enable fallback hotspot (captive portal) in case WiFi connection fails
#ap:
  #ssid: !secret wifi_ssid
  #password: !secret default_pass

#captive_portal:

# Example configuration entry
i2c:
  sda: 4
  scl: 5
  scan: true
  frequency: 400kHz

#Sensors should be specified as follows
  #platform: bmp280
    #i2c_id: bus_a
    #address: 0x76

sensor:
  - platform: custom
    lambda: |-
      auto sht20 = new SHT20();
      App.register_component(sht20);
      return {sht20->temperature_sensor, sht20->humidity_sensor};
    sensors:
    - name: "Temperature"
      id: inside_temp
      unit_of_measurement: °C
      accuracy_decimals: 2
      on_value:
        - mqtt.publish:
            topic: "FamilyRoom/esp8266/sht20/temperature"
            payload: !lambda |-
              return to_string(id(inside_temp).state);
    - name: "Humidity"
      id: inside_humidity
      unit_of_measurement: "%"
      accuracy_decimals: 2
      on_value:
        - mqtt.publish:
            topic: "FamilyRoom/esp8266/sht20/humidity"
            payload: !lambda |-
              return to_string(id(inside_humidity).state);

# Example configuration entry
mqtt:
  broker: 192.168.55.200
  #username:
  #password:
