# https://esphome.io/components/substitutions/
substitutions:
  device_name:              wt32-eth01-basic
  device_name_friendly:     WT32-ETH01-BASIC
  mqtt_location:            "Office"
  mqtt_device:              $device_name_friendly
  api_password: !secret     wt32_eth01_basic_api
  ota_password: !secret     wt32_eth01_basic_ota
  broker_address: !secret   broker_address
  led_gpio:                 GPIO2
  device_ip:                192.168.55.232
  network_gateway:          192.168.55.1
  network_subnet:           255.255.255.0

# The ESPHome section sets the required node name and optional settings.
# https://esphome.io/components/esphome/
esphome:
  device_name:   ${device_name}
  friendly_name: ${device_name_friendly}
  area:          ${mqtt_location}
  comment:       "https://en.wireless-tag.com/product-item-2.html"

# https://esphome.io/components/esp32/
esp32:
  board: wt32-eth01
  framework:
    type: esp-idf

# https://esphome.io/components/ethernet/
ethernet:
  type:      LAN8720
  mdc_pin:   GPIO23
  mdio_pin:  GPIO18
  # clk_mode: GPIO0_IN
  clk:
    pin:  GPIO0
    mode: CLK_EXT_IN
  phy_addr:  1
  power_pin: GPIO16
  #Optional manual IP
  # manual_ip:
  #   static_ip: $device_ip
  #   gateway: $network_gateway
  #   subnet: $network_subnet

# https://esphome.io/components/esp32_ble_tracker/
esp32_ble_tracker:
# Optional: For better reception, you can set interval and window equal
# scan_parameters:
#   interval: 1100ms
#   window: 1100ms

# https://esphome.io/components/bluetooth_proxy/
bluetooth_proxy:
  active: true # Enables proxying active connections (default is true)

# Enable the Home Assistant native API.
# https://esphome.io/components/api/
api:
  !include Components/Core/api.yaml

# Enable OTA updates.
# https://esphome.io/components/ota/
ota:
  !include Components/Core/ota.yaml

# Enable logging.
# https://esphome.io/components/logger/
logger:
  !include Components/Core/logger.yaml

# Enable I2C communication.
# https://esphome.io/components/i2c/
# Note that the original i2c_esp32.yaml file uses GPIO21 which is not allowed for the WT32-ETH01 anymore.
# i2c:
#   - !include Components/Core/i2c_esp32.yaml

# The text_sensor handles many MQTT publishing duties.
# https://esphome.io/components/text_sensor/
text_sensor:
  - !include Components/TextSensor/ethernet_info.yaml

# Enable MQTT publishing.
# https://esphome.io/components/mqtt/
mqtt:
  !include Components/Core/mqtt.yaml

# The interval component handles many MQTT publishing duties.
# https://esphome.io/components/interval/
interval:
  # !include Components/Core/interval_ip.yaml
  - interval: 1min
    then:
      - mqtt.publish:
          topic:   "$mqtt_location/$mqtt_device/mac"
          payload: |-
                   return id( text_sensor_mac_address ).state;

# Expose the node state for Home Assistant.
# https://esphome.io/components/binary_sensor/
binary_sensor:
  !include Components/BinarySensors/status.yaml

# Safe mode used to be part of the OTA component.
# https://esphome.io/components/safe_mode/
safe_mode:
  !include Components/Core/safe_mode.yaml

# https://esphome.io/components/sensor/
sensor:
  # https://esphome.io/components/sensor/internal_temperature/
  - platform: internal_temperature
    name:     "Internal Temperature"
