substitutions:
  name_of_device: basic-esp32
  device_name_friendly: BasicESP32

esphome:
  name: $name_of_device
  friendly_name: $device_name_friendly

esp32:
  board: nodemcu-32s
  framework:
    type: arduino
    version: recommended

logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid_work
    password: !secret wifi_pass_work

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
