substitutions:
  device_name:          basic-esp32
  device_name_friendly: Basic-ESP32
  mqtt_location:        "Mobile"

esphome:
  name:                $device_name
  friendly_name:       $device_name_friendly

esp32:
  board: nodemcu-32s
  framework:
    type:    arduino
    version: recommended

light:
  - platform: status_led
    name:     "Onboard LED"
    pin:
      number:   GPIO2
      inverted: true

# Enable logging
logger:
  level: VERBOSE
  logs:
    mqtt.component: ERROR
    mqtt.client:    ERROR

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  id:              wifi_id
  power_save_mode: NONE  # Options are NONE, LIGHT, and HIGH, with HIGH saving the most power.
  networks:
    - ssid: !secret     wifi_ssid
      password: !secret wifi_password
    - ssid: !secret     wifi_ssid_work
      password: !secret wifi_pass_work

mqtt:
  broker: !secret broker_address
  topic_prefix:   "$mqtt_location/$device_name_friendly"

sensor:
  - platform:        wifi_signal
    name:            $device_name_friendly WiFi Signal
    update_interval: 20s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: $device_name_friendly IP address
      id:   ip_address
      on_value:
        - mqtt.publish:
            topic:           "$mqtt_location/$device_name_friendly/ip"
            payload: !lambda |-
                             return to_string( id( ip_address ).state );
    ssid:
      name: $device_name_friendly connected SSID
    bssid:
      name: $device_name_friendly connected BSSID
    mac_address:
      name: $device_name_friendly MAC Address
      id:   text_sensor_mac_address
    scan_results:
      name: $device_name_friendly scan results

interval:
  - interval: 1min
    then:
      - mqtt.publish:
          topic:           "$mqtt_location/$device_name_friendly/mac"
          payload: !lambda |-
                           return to_string( id( text_sensor_mac_address ).state );
