substitutions:
  name: tdisplays3
  friendly_name: T-Display-S3

esphome:
  name: "${name}"
  platformio_options:
    board_build.mcu: esp32s3
    board_build.name: "Espressif ESP32-S3-T-QT"
    board_build.upload.flash_size: "4MB"
    board_build.upload.maximum_size: 4194304
    board_build.vendor: "LilyGO"
  on_boot:
    - priority: 800
      then:
        - lambda: |-
            id(disp).enable();
            id(disp).transfer_byte(0x11);
            id(disp).disable();
    - priority: -100
      then:
        - switch.turn_off: backlight


esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: !secret default_password

captive_portal:

spi:
  clk_pin: GPIO3
  mosi_pin: GPIO2

i2c:
  sda: 43
  scl: 44
  scan: true
  frequency: 400kHz

font:
  - file: "fonts/OCRAEXT.ttf"
    id: fontocra
    size: 42

switch:
  - platform: gpio
    pin:
      number: GPIO10
      mode:
        output: True
    name: "Display Backlight"
    id: backlight
    entity_category: diagnostic

time:
  - platform: homeassistant
    id: home_time
    timezone: Europe/Amsterdam

display:
  - platform: st7789v
    model: Custom
    width: 128
    height: 128
    offset_width: 0
    offset_height: 0
    backlight_pin: GPIO10
    cs_pin: GPIO5
    dc_pin: GPIO6
    reset_pin: GPIO1
    id: disp
    rotation: 180
    lambda: |-
      it.strftime(0, 0, id(fontocra), TextAlign::TOP_LEFT, "%H:%M", id(home_time).now());
      it.line(0, 50, 128, 50);
