#The substution block has all the configurable details
substitutions:
  name_of_device: m5stampc3
  device_name_friendly: M5StampC3

esphome:
  name: $name_of_device
  friendly_name: $device_name_friendly
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    # type: esp-idf
    type: arduino
    version: recommended

logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid_backup
    password: !secret wifi_password

mqtt:
  broker: 192.168.55.200

sensor:
  - platform: wifi_signal
    name: $device_name_friendly WiFi Signal
    update_interval: 20s

# ATH20
  - platform: aht10
    temperature:
      name: $device_name_friendly AHT Temperature
      id: inside_temp
      unit_of_measurement: °F
      accuracy_decimals: 2
      on_value:
        - mqtt.publish:
            topic: "Kitchen/m5stamp/aht20/temperature"
            payload: !lambda |-
              return to_string( ( id( inside_temp ).state * 1.8 ) + 32 );
    humidity:
      name: $device_name_friendly AHT Humidity
      id: inside_humidity
      unit_of_measurement: "%"
      accuracy_decimals: 2
      on_value:
        - mqtt.publish:
            topic: "Kitchen/m5stamp/aht20/humidity"
            payload: !lambda |-
              return to_string( id( inside_humidity ).state );
# BMP280
  - platform: bmp280
    temperature:
      name: $device_name_friendly BMP Temperature
      oversampling: 16x
      id: inside_temperature
      unit_of_measurement: °F
      accuracy_decimals: 2
      on_value:
        - mqtt.publish:
            topic: "Kitchen/m5stamp/bmp20/temperature"
            payload: !lambda |-
              return to_string( ( id( inside_temperature ).state * 1.8 ) + 32 );
    pressure:
      name: $device_name_friendly BMP Pressure
      id: inside_pressure
      unit_of_measurement: "hPa"
      accuracy_decimals: 2
      on_value:
        - mqtt.publish:
            topic: "Kitchen/m5stamp/bmp20/pressure"
            payload: !lambda |-
              return to_string( id( inside_pressure ).state );
    address: 0x77
    update_interval: 20s

i2c:
  sda: 18
  scl: 19
  scan: true
  frequency: 400kHz

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results
