substitutions:
  name_of_device:       esp32-18650
  device_name_friendly: ESP32-18650

esphome:
  name:          $name_of_device
  friendly_name: $device_name_friendly

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  networks:
    - ssid: !secret     wifi_ssid
      password: !secret wifi_password
    - ssid: !secret     wifi_ssid_backup
      password: !secret wifi_password
  ap:
    ssid:             "$device_name_friendly hotspot"
    password: !secret default_password

mqtt:
  broker: !secret broker_address
  topic_prefix: "$mqtt_location/{mac_address}"

captive_portal:


binary_sensor:
  - platform: status
    name:     $device_name_friendly status

sensor:
  - platform:        wifi_signal
    name:            $device_name_friendly Wi-Fi strength
    update_interval: 20s

text_sensor:
  - platform:        wifi_info
    ip_address:
      name: $device_name_friendly IP address
    ssid:
      name: $device_name_friendly connected SSID
    bssid:
      name: $device_name_friendly connected BSSID
    mac_address:
      name: $device_name_friendly MAC Address
    scan_results:
      name: $device_name_friendly scan results
    update_interval: 120s
