substitutions:
  name_of_device: esp32-18650
  device_name_friendly: ESP32-18650

esphome:
  name: $name_of_device
  friendly_name: $device_name_friendly

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "aSZGaJ+Kas/c3pm2yhpU77OD75VtRQq4n6vFQbvoj7s="

ota:
  password: "65f62ee1c71c065fe336a3801b650f8c"

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid_work
    password: !secret wifi_pass_work

mqtt:
  broker: 192.168.55.200

captive_portal:
    

binary_sensor:
  - platform: status
    name: $device_name_friendly status

sensor:
  - platform: wifi_signal
    name: $device_name_friendly WiFi Signal
    update_interval: 20s
