substitutions:
  name_of_device:       esp32-bme280
  device_name_friendly: ESP32-BME280
  mqtt_location:        "BackYard"
  mqtt_device:          "ESP32"
  mqtt_sensor:          "bme280"

esphome:
  name:          $name_of_device
  friendly_name: $device_name_friendly

esp32:
  board: esp32dev
  framework:
    type: arduino

#deep_sleep:
#  id:             "deep_sleep_2min"
#  run_duration:   '30s'
#  sleep_duration: '2min'

status_led:
  pin: GPIO2
#  pin:
#    number: GPIO2
#    inverted: true

#output:
#  - platform: gpio
#    pin:      2
#    id:       onboard_led
#
#light:
#  - platform: binary
#    name:     "Built-in LED"
#    output:   onboard_led
#    id:       led_light

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key_bme280

ota:
  password: !secret ota_password_bme280

sensor:
  - platform:            wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name:                "WiFi Signal dB"
    id:                  wifi_signal_db
    unit_of_measurement: "dB"
    accuracy_decimals:   2
    update_interval:     30s
    entity_category:     "diagnostic"
    on_value:
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/rssi"
          payload: !lambda |-
                           return to_string( id( wifi_signal_db ).state );
  - platform:        bme280
    temperature:
      name:                "BME280 Temperature"
      oversampling:        16x
      id:                  bme280_tempF
      unit_of_measurement: "°F"
      accuracy_decimals:   2
      filters:
        - lambda: return ( x * 1.8 ) + 32.0;
      on_value:
        - mqtt.publish:
            topic:           "$mqtt_location/$mqtt_device/$mqtt_sensor/tempF"
            payload: !lambda |-
                             return to_string( id( bme280_tempF ).state );
    pressure:
      name:                "BME280 Pressure"
      id:                  bme280_pressure
      unit_of_measurement: "hPa"
      accuracy_decimals:   2
      on_value:
        - mqtt.publish:
            topic:           "$mqtt_location/$mqtt_device/$mqtt_sensor/pressure"
            payload: !lambda |-
                             return to_string( id( bme280_pressure ).state );
    humidity:
      name:                "BME280 Humidity"
      id:                  bme280_humidity
      unit_of_measurement: "%"
      accuracy_decimals:   2
      on_value:
        - mqtt.publish:
            topic:           "$mqtt_location/$mqtt_device/$mqtt_sensor/humidity"
            payload: !lambda |-
                             return to_string( id( bme280_humidity ).state );
    address:         0x76
    update_interval: 20s
  - platform:        wifi_signal
    name:            $device_name_friendly Wi-Fi strength
    update_interval: 20s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: $device_name_friendly IP address
      id:   ip_address
    ssid:
      name: $device_name_friendly connected SSID
    bssid:
      name: $device_name_friendly connected BSSID
    mac_address:
      name: $device_name_friendly MAC Address
      id:   mac_address
    scan_results:
      name: $device_name_friendly scan results

wifi:
  power_save_mode: NONE  # Options are NONE, LIGHT, and HIGH, with HIGH saving the most power.
  networks:
    - ssid: !secret     wifi_ssid
      password: !secret wifi_password
    - ssid: !secret     wifi_ssid_work
      password: !secret wifi_pass_work

mqtt:
  broker: !secret broker_address

i2c:
  sda:       21
  scl:       22
  scan:      true
  frequency: 800kHz

interval:
  - interval: 1min
    then:
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/mac"
          payload: !lambda |-
                           return to_string( id( mac_address ).state );
      - mqtt.publish:
          topic:           "$mqtt_location/$mqtt_device/ip"
          payload: !lambda |-
                           return to_string( id( ip_address ).state );
