substitutions:
  name_of_device: armada-sht30-01
  device_name_friendly: Armada-SHT30-01

esphome:
  name: $name_of_device
  friendly_name: $device_name_friendly

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "O5I+AON66eIzuMGtYQFBYB5SA8rFwZc+qFJlRMIENuk="

ota:
  password: "930f4ae76dcbb47f18d72e27fc759ff5"

sensor:
  - platform: sht3xd
    temperature:
      name: "temperature"
    humidity:
      name: "humidity"
    address: 0x44
    update_interval: 20s

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid_backup
    password: !secret wifi_password

mqtt:
  broker: 192.168.55.200

i2c:
  sda: 21
  scl: 22
  scan: true
  frequency: 400kHz
